import math
# Default game settings file, define consts here

# game res
G_RES = WIDTH, HEIGHT = 1600, 900
G_FPS = 60
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2

# player consts
PLAYER_POS = 1.5, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.003
PLAYER_FIRE_SPEED = 0.0025
PLAYER_FIRE_SPEED_PISTOL = 0.002
PLAYER_FIRE_SPEED_SUB = 0.0015
PLAYER_FIRE_SPEED_CHAIN = 0.001
PLAYER_ROT_SPEED = 0.002
PLAYER_FRICTION = 0.0003
PLAYER_SIZE = 64
PLAYER_MAX_HEALTH = 100

# mouse consts
MOUSE_SENSITIVITY = 0.00015
MOUSE_MAX_REL = 40
MOUSE_MAX_REL_Y = 100
MOUSE_BORDER_LEFT = 600
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT
MOUSE_BORDER_TOP = 400
MOUSE_BORDER_BOTTOM = HEIGHT - MOUSE_BORDER_TOP

# rays and fov
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

# screen rendering
SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

# misc
TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2
GLOBAL_TRIGGER_TIME = 100
G_SOUND_VOLUME = 0.1